# Generated by Django 4.2.6 on 2023-10-12 18:42

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(help_text='user name', max_length=100, null=True, unique=True)),
                ('password', models.CharField(help_text='password', max_length=100, null=True)),
                ('email', models.CharField(help_text='email', max_length=100, null=True, unique=True)),
                ('first_name', models.CharField(help_text='first name', max_length=100, null=True)),
                ('last_name', models.CharField(help_text='last name', max_length=100, null=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[(0, 'male'), (1, 'female')], help_text='gender', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='updated at')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
