# Generated by Django 4.2.6 on 2023-10-17 16:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('code', models.CharField(max_length=256, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, help_text='description', max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='updated at')),
                ('create_by', models.ForeignKey(blank=True, help_text='created by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_country', to='account.account')),
                ('updated_by', models.ForeignKey(blank=True, help_text='updated by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_country', to='account.account')),
            ],
        ),
    ]
