# Generated by Django 4.2.6 on 2023-10-12 18:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(blank=True, help_text='name', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='description', max_length=100, null=True)),
                ('url', models.CharField(blank=True, help_text='url', max_length=256, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='updated at')),
                ('created_by', models.ForeignKey(blank=True, help_text='created by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_type', to='account.account')),
                ('updated_by', models.ForeignKey(blank=True, help_text='updated by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_type', to='account.account')),
            ],
        ),
        migrations.CreateModel(
            name='PostStatus',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(blank=True, help_text='name', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='description', max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='updated at')),
                ('create_by', models.ForeignKey(blank=True, help_text='created by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_status', to='account.account')),
                ('updated_by', models.ForeignKey(blank=True, help_text='updated by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_status', to='account.account')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(blank=True, help_text='name', max_length=100, null=True)),
                ('title', models.CharField(blank=True, help_text='title', max_length=256, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='description', max_length=2048, null=True)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('meta_keyword', models.CharField(max_length=256)),
                ('keyword', models.CharField(blank=True, help_text='keyword', max_length=256, null=True)),
                ('short_content', models.TextField(blank=True, help_text='short content', max_length=2048, null=True)),
                ('content', models.TextField(blank=True, help_text='short content', max_length=2048, null=True)),
                ('slug', models.SlugField(default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='updated at')),
                ('created_by', models.ForeignKey(blank=True, help_text='created by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_post', to='account.account')),
                ('status', models.ForeignKey(help_text='post status', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_status', to='post_app.poststatus')),
                ('type', models.ForeignKey(blank=True, help_text='post type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_type', to='post_app.posttype')),
                ('updated_by', models.ForeignKey(blank=True, help_text='updated by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_post', to='account.account')),
            ],
        ),
    ]
