# Generated by Django 4.2.6 on 2023-10-12 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('post_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostType',
            new_name='Category',
        ),
    ]
